apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  cluster: production

resources:
- ../../bases/cluster/
- ../../bases/findingway/
- ../../bases/clearingway/
- ../../bases/dividingway/
- ../../bases/moddingway/
- ../../bases/old-findingway/