---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: env
  namespace: findingway
spec:
  encryptedData:
    DISCORD_TOKEN: AgAYuzOxcaHkex/uLiBbJtoFE3MW9TAkhCZxoGtVNpdLkz7TCI/keOVkSEv8bbbZJKCko6jrMJ1/huhT2VVWfDmTstbyPuVbx4Z2hhYQKq7a/hMuIl+CsaTCK9rJiesndV8LRPqvZf0TvM2HMYeypvSUWJWmPCP4HTyZyTKg+evtUjggJf9oV3BbnfjEuzbxJD20UHxMGLc9FKXSM3dVKhoaq64LdMCkXujU4lSWUt960y2UGn13RSq0vPubeEX1ZdNXP1T92EgTy3mVe/ZpUxRnM49QRaJ+mxIGaBwQX3a23o/CxxzTM38oJRqBm+PoIUm0jriDLUanK/iT5b80gpMxLqFgpPxdEQvZrXKQst3LXuGY7B234B8/ZDTTN2qN1z1BacBIps/1mskibXdrBu3PvcVCe02jr5nzrsKDdYhjL7ObH4FIzlgRWVNU+vAbgs+2TOekN8Fh7dTrM96kNH7CK6zxneM1NMlKsewWQxTQMWnsjeR7ARD5jQN1pKgfGMXlXszsW/7g6GF3jfHyXNeGgAVmQLUsFgT5xhAMQhivqhL3H+rCviLwyLCDp+V9oxCvCyaWK8VGJHKNq+Zs+A/3GcEVcHyC1VRZrCksYVcIbdtQgOU5LiADFdQGPoeIbxbK1IjIjrbme+AlOwgFpDR08x43lXxsllq52m27EowkjLzcGXMfTolfTxXgzPZ1vXYOyIomSziMFnAU8kc4koj+DFTxnQluHErB1hsCucxoA42hXm5JKM3i8ukCMv4HGHwYleGBiuty80XOIb/92wwQWJgccii8pQ==
  template:
    metadata:
      creationTimestamp: null
      name: env
      namespace: findingway
