apiVersion: apps/v1
kind: Deployment
metadata:
  name: pruner
  namespace: findingway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: findingway
      component: pruner
  template:
    metadata:
      labels:
        app: findingway
        component: pruner
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      imagePullSecrets:
      - name: github
      containers:
      - name: pruner
        image: ghcr.io/naurffxiv/findingway/pruner:sha-047e78c
        envFrom:
        - secretRef:
            name: env
        resources:
          requests:
            memory: "128Mi"
            cpu: "125m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL

