apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper
  namespace: findingway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: findingway
      component: scraper
  template:
    metadata:
      labels:
        app: findingway
        component: scraper
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      imagePullSecrets:
      - name: github
      containers:
      - name: scraper
        image: ghcr.io/naurffxiv/findingway/scraper:none
        envFrom:
        - secretRef:
            name: env
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL

