---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: env
  namespace: findingway
spec:
  encryptedData:
    FINDINGWAY_DISCORD_TOKEN: AgBQImhlC0aOvzdcOm/gVm/Ire3cxl+tSbwN4P9TOxpTOQERmlfYbOZZXmMsTxiCcHWwkG+/Bl5r11hyOoPhtWkcmm2JZxD/aL4nqLCYhp3eZ1ljwaVNPoDghDfEs7QcMDFtKCKsqk3/re8ZpCrOrmKJ9+5G+KosCcRE17dWLdeMSOFXoYvSOeCtu7UqO0oeyTf+HzrLjFGn4okgbZYZhRKzVRANWP5Q/f8GYtoXSA8EikAv1j3axMacqV72tz/UjHkWqcEnTbS3ljwbm0ftbBnVgrAg9Va8478H80BO0bad8C4pR6EQ6W7OPk7jwv9Qqk4jy7cAssncGkc4sI9splfF/m22B8oWL/h3aSkBxH3k44d/yTPIfKElqC8MmNtuMYLgZVdASZiOnfIvRYIECQjUipFnMQKktpPdOtn/oA8JVz4sGty8dPsBR3Sv1KRoQ9R4Gzwqt4aAezXw06rWLBblSTS8jKgF0Ai/zPB64szdzyYjJ+IlJ+zYINYgsY46V4LZ16Wnv30KTtogbTMN6dyfG6ahV4yUHHrmaQa8zbr9+cdhboJHwO7PPmwOkYcDHg8+25I6k+uIXkXkgnEj+2gu5n4AtfoiR89oN3HHnm+ojciKNtqiID9YmoKKsVKRDJQAqgMggFRDQJPPDVFVV5cHSnwKBmavSh9YA6sv9/hiYc7a5AZSmkGoMdDECYc26kSzl+ew/tFIWuPDJkuor18HMlujX/cz08H3blzXuRgqJG1p+lWR5ObTGqPCcaRpwhDRp0J50ZUneZsN3F9dUEDesbxFnM9U/8M=
    FINDINGWAY_POSTGRES_URL: AgBdZV3fN3NMuMFwtZA+/WUosdOE0UgzrobaDO5NhkrrdsJgv9mUd6pEny65qw/z39Je9sXnwAfS/KAHZ080IPthWDYe+rN3ekYMkWnLN6Lzyzt8bXuCrZUUs6rfltjKGobOwSQ89ZgjNNnd4oS6xuSg1fLPcAX8RDxs/Y7U7B5Ik11wa66oPpKp1VSG2tS535+dYfd8xYc5F4YoA/OtQt2JtNdZzIhzPb1qO06EEGWDM/qBHZ1wIX34EMatoaootFXzkus7+xU5uX4+FJFtco8AGSqBVS1T+9//LzUzQpv5AgwNS+2bN99G6U/FR7xHbk+sfLfxZt38jKSKekJAoGY1M309vnEtfaKYGMnxQYsb708V+2h94Q5u2Vu2Qc+P4me2q+cMbeeKVPQDLDF/VEUGo5LQNVTO/zQ+95yh2+6vb8HbIst9gFMSClrhu9dbt3a7wYbiuFQNsKuxyd+tlyBvazTMknOGA62rtPgwoTWyU+KLdxU8J7Qe01VTQswR77XLRGAVjcd9YvvxGR/ubYVhCdQsItxtL/1jXSBrI7+gBjMwQbIY4kncCIKMogs3BRcGdff7Q/wvRYRMdsh7rpfXsY3FL7TMCP+bGYAwfGrpSX/BAE1Uw1vxIZyRrf/iGTTmVxUoFhfG+REzv22vgRN3J6Nzspi9BLFjOt8h3NXpYh0hwRtl49rWbExddhXtVg5DfSoGFSE5fEXQoTR6sJH5t68EbVzMxd6VCnYpaMS0KemZfnTcUJGYJhZxkjNTgDgqC186JmWtF95RrJdTJOIwW1+f8Wb78hVkhKgynTre1FQaUD/uR6OP039yoB3ZjACq57stBgF/9x8LANCWaCvCjz+l1hRqXxybLebuCd+A6wDhOQ==
  template:
    metadata:
      creationTimestamp: null
      name: env
      namespace: findingway
