---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: env
  namespace: findingway
spec:
  encryptedData:
    FINDINGWAY_DISCORD_TOKEN: AgAKrg4ipQMQJ5fHT3rIWLMFOPwVqp/epR6AxgoZISDiKspECV8IIUQqGpQmuWWYdwrPoHxBNcqyMP9R32+laoCMBy1OdGZpOKoGZsZurRM8quVpwgbvZbnhxu91ofPPlBnOhzghic5rFB0hTfYwQ4SKofwpnGV6Q3Kv9DPimrY8GZsEAaIlzc7JOnLdHMMDuTElp5BwxV5xDFaTCm0owkcvF8ryxCQXZqt7qkqUuxdcQGV70lbPy3jHEtNSH4OE+jQHQWoP9qcwfOCZ2zMf6pB8aAhMD8x11hDMTxU/n5M0zSC6TAVZkd8XJHk20VBFoRL6fpW0BtLj4mUmSIqRgBqoIzYh820AXiKiIRcdH1xd5Z8+1BqpAbCJ4EaTkj4iCf1cGX4zryAHI+fosnl7oJOfMTTNZ+iJSuEpIvVjgFw0KHx5vLCfvN1ufGrEs3dpxOOEQ2V3pgNO2QJCFygNF+4e/twEEsLloBd6zsJscw7n/WURSp1xXwZj2nYwUo0jOBhsYp9Yzb+WmkvlJt9yYMcst2Llc/YThQqPK7+HjTQI1WCnHDdYFBkq2waVxWToGY7Y+yZGZoaY4KtMkdpNc8L/1d/BF6eaxlFdZWC77Uyh3PCkUf3TUyZ5Fajqm2QlwyWkeOwhSUrO03BZg+w2diZkbUOoSdyVLmM06fwlhSi2tEAdt6OX75skO7gmxri0taiCBt17R1gEHacjXkc2riUMjql7/kgNcjKFMY/PU6ME3HgHY0JYrghYvsxzWvm932jczk2gnAddMrlJG+usD+aAlB7cHnCwUro=
    FINDINGWAY_POSTGRES_URL: AgACERPXj5FqsKt+wpKVENrFUHI1T7SUjGdvwfdOg/B+iVjWRLY/RuVpPF+G8pWAOwoVcLaqGXdTTfvAmVC/SIX6GHYT7zDy33JYXVLDtEylE22wcUNrJvrQGFAKdZNC74w0J+KcqpFnWYgt2dtzxruAOLJIACWrKy/s8azq88OgPvS7cFT4fUgB6ctlplXSYPIH0qp54+oinNZbZPqSsm0x0ZbWWISFsNOd0FywaYO+4mXhCan5xy3iZRivnVWYIhJwDMamiLmPsZpDpKfdpURnTbQ3wijcsJ55n14dDfrpT8IaB306IrtCM3HCBQ2JElE6jw1h7Euyd2RSJdJM5gQub0Wi5MkZRV2dmDOpXTmeZNXc0R8q2wEdU7+wNrq+n/uWFtlXn7OkhkEM7jS90/iSv+++x4bszymssU9auvunMAosB0U4VDHEQO+OpsopnmT9MsJ2TEGmPBZQ2Uv+aHxMQVGXpUXGxpVmeIgUf5/gG/g+fryUxq2tGsAxppHtmjd0kAGOku5qC5sfSllmsWbddksyBEaNn9vPoI6Cj3+gZoI58EvLL6CIxBIHWD8M4ott1zzR2RcsFNROuUeGX9jNbKat/P4nootjd+EHOPt/ndCyCffNufD64dVl4o3u8ZHjAjBA6NsZYN1RxkIm6YSnbNOnV4srI4qAHNpjZ7IC3if6m8l8xpW/OMW33x6e3nDW3Igi8ieSkkOc1flKAY34VkKNSFHBEupxpbLJOTcIJrrLgH5zGmOHpBhbuOfEi6miBkZ06Qd47TykRIG7+NxIOevwFh/g++ReO7IbLeX1YCkYBbrRcgpejaI27NDY/z8h41KWvbJSJvcZzGdG2y/bfIDvQ3jDMW6iXSb3lOh4ocOhiA==
  template:
    metadata:
      creationTimestamp: null
      name: env
      namespace: findingway
