---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: env
  namespace: findingway
spec:
  encryptedData:
    FINDINGWAY_DISCORD_TOKEN: AgCLFONOeCQlzBXjrnBeQypu1GsQOSD9Mz3Q+AuHTGNYx+CzMLfLvqUR3pBmtsGK8LkKQwk/oPoajxKX/ROqZP32okJjI+O0Atk9HTu7dnpgZHbWkznTssIiklDUBahSvZ5yqFTLtqlLICkm28aUDIVislR9uu8CntOoqUDJjcv8ZiFKZW4KhG86zwzaN/NrT3aK9XbIIVjYPKOjYDIuC/F6njT2qYJ8O+evr7Y+C0W6gNyZ6Wq+jVt1YSfOA3MAc9PFe+LbAv6LzMMxZylc0oZRc78ZR52alLySz9lEBel2pvYTjqm58Lk4MOG+RzaD/rP0rYxAkw386702FFe/5NA8OUGcTaqUsMtgpWind5/oVsLvke/h/5S7DSpK0XALQREY33DbMfx9voWg6B4VCGgkSwxe9dC7GYJJu242LhgjJFhVT5L+njOI1cxEG2lXtRrQHFRi9520/wm6HezniDwQoP3efK0HsyOJcPSiINGFFc4QyXkgPQAn57ht70xOtrSh1Sj14r5ouqWsmp3X+pKYeUc0S2gjN7bGjpTMecyevteg7/bP7coZwzNXDkTcnI0GDlfPQ2Zp35CqtmFtvY1n+P/32nzsb5buHlQV8ELW3mfmnwrWrlrRxuYnTeQDmc6wzjkq3EGc38n+wGm53Peo4NXLUX1YFoM7Woomr9CGG259ErZePGtXepsUdwRpRAVI/vuEF1AYp0tsza6odudqhzsEE+qkw0o08A+hOZrjPbu+iXoKjOh/TkLzKSWrocM/I+1o8iYn3regdro4QV+rJfImCRLhv2A=
    FINDINGWAY_POSTGRES_URL: AgACdTd2HIMc/DDysnRfMvfxUQWh/FPrIcXtWRLIKzy17yIOHsRd94vAAneaHwm9FRqf9LuT8cbdlYRil9fCOq7VTi4yC149IwpXG5CZgJEoaNSQ6hPbW4HVusv3ksJllZp6rGN+uLlNmoYvFFBnLvmW5d+qKLdabkTVyQuDCwubBcqiPhlaW+wxOgMnHf5GneycWTNdRD4w+BlHzHLuheC2vq0eZRjCALmhPn4ktqfHAXsz8hXuzysEnZupQIKqk4fmyiI57hIgkM1Q+xcnMwT2gQZY4MsBhOmaST6AbyiOAMyTAu/EgMtotwprKfjEJ8aJiyVOEb8caomItxzpjM2DC7tTTqkKY8ZDK23wE1oP2l1JVXb8lUEUJtBPD+bpRiG9QctWJ4Mq+1RW2o1iyijRWogdxmP/XR2ym99Bmv5Idb+BsDDY54uG5zxZL6pL/YbSnAO9k/aE2btiRijFliNrhJOUgqfcIDiRBCsZDfIjiIgEOAmQuPeBnyHv3J4bGPBVQGvHewtLLFpfbtzxR7zQQiIkc+fp7I1ZnhXOgW60Ag9lflF30K9QmAfitX4b34jejyPDafEkn+OTmOJoip0Cs/gZo+Ml9JN/Tt9BgOWzamcXuWh1QXPtT6ESZCFYpKr4Ikl92BruyF0IwUCJ4XxgLtVj6NsJfejdCmbIqfTSQTiuV4EOfjQjcdfKNdpUoIuJOhZAqq44hjh+uvUykZiPGZ86hln+C/3Qu0bLaFONAGcJdqhbwj5CJCJs7Xvh/DHLIBIhpPE0Z2U1SU/CiMoHcfu6XCIX63I0KAX4B5WlfrcLTmBa+vdZWYrYLKBibmV66MnYfWurxgtVdNXH4kkPmreGoMeI7TBPeiggugtLTRGeuw==
  template:
    metadata:
      creationTimestamp: null
      name: env
      namespace: findingway
