---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: env
  namespace: findingway
spec:
  encryptedData:
    FINDINGWAY_DISCORD_TOKEN: AgCItEcdU6dT/FYX51/1ya6JmBKFJWY+OukyuLb3xdEQl293YGFhGJVYhq890kDDdvBJhUodRB4aLMpKk1SDz3It/OA02vvJA6EIBO5SAJ2/23+yZdTMIFYml9h3hb7BavklGZEpa5xJY2Sl3KwnrKJFURBmoCSZRFT+aLb7zRU2a11/D5fFD9+MaVv/ro+XvUWBpwk/Vpu1bQTJFSA3LA9gVx49mDAMmlUYs9SUCa95qR0HxcMs5jqSrW6jbYWbeDZfKrw5ub5VbL6gCdcayJ8aKD81WZb1R70nO9577JBnN2SdtPmhonM3oomFsLDaaLchwzWAcvTC2lXQs4UPi1Zj+GPWtxxkbzzuqNGiwIytUw9USPCGF58rGGaAfFAD6l7+sYRlfFqG3xY7DYA8gphGZGStSkDKsABYe1lvmwpThdCINp593anffvEix4Ep08vDG/uj+OuJtS0LXWBDuhtZRVYvyopVlY9PLYeSGetubUubAQZwKkC0A9U1LikV7qSk02F6KWytJ3xCxDM/zz0gxjMhaeBZeYQrUQkOXUttoHGVw4oxx3G8aguisoteX8atsk1BegOwMvFlq7OZXbLTG8SwZ1kzZf18TzqrOxC/IoC6bVZ/HiriUFv8+NiizBsOhkRRG4NzOLFw0jZwCDZ+OSTi9gm6hHOqJKlCSgFbV2Mxo3vYZWBIrvyP9nlIpGTCC+yIkDRKmhNMVp/U7+9LloyZEkQoQUIzb5iw5Ezhhl3NR3npWxbeHO/g/8Sf1YSlPYfoB8R3yBDgCbh4bG/IOv00pjh1kCk=
    FINDINGWAY_POSTGRES_URL: AgCdvtfBqk0IcesrN+8tYkqBhZLlLVBarSSpu9FDJKrdg0Jm8YbXAcdS2ZNYGUHzP9ZRBm0EAO8az6UomeTHFRDTC4TPSQCbu70o7Ga6gznn3uVeHDSsB02GzP5k9l5BOv0Is4fbl8W10LSowcOkkTtQX4/4TBgy/sfze4aIzDcSCJoXK/2rZ+jZB2b3dZWaqcP+W0vq44zzexue7dAJl/HyJe92MctcpOPWK/Bacz1wB2Ap2cKRDg1XYte2K3vOMTuNm0qlFn+CMvQuggLENmt7hDPjiqGNYTuQYtK+0ZknYQOs8igNOg1L8KwS3oYWarpGJmw4rEYkXFe71J2c4XTzC6CHZ4z8Jci6PYGGYSlpNCCUhpQAe2e4y+QsukXow6InidsepiR2l6QT9Nw15KMkZ6af9YrKjnZIZsVg2hQ7AHurSly7kS6vl7qWwoZ9m459eAX1tNHIU0i1Lo81De8NSX8HIs5DcC4jaKLBzydnsZBYR+UIZaxNFWf2bohojkz/LzhC6GWslWQxAGIPKWPUBnkB0e6NeUaLP8z1z4xVRjo6dyfZdwd6ven21zPO0ubwuFjHFqxwxkWje4MgzGH9lZxxb5o80VIHRpwL+98P0cSlsMiwKOqbmRhCnB3EEVq1WD/FOF2aGEe95WB+4yCYNZld9V9OeNVAp/wZcFhoZrb4aUKzxuxAYKw3G8ZsEzMSfJiGTaMkXAV+gPWmu7qgFAtimupF7A35OS7+fjdxBD/mC0idyN1WHlAjmmFOjXvfdFU+PnJrFAau8MJQVDF4+364Ek4qyfDVlYlEvCWIJhiC2mgCzZivGo2MRTnRRZ7iT2J/ciUYzSB6jaubmrxJRlqamRFk7W4GeGDa8vtNWNXtPw==
  template:
    metadata:
      creationTimestamp: null
      name: env
      namespace: findingway
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github
  namespace: findingway
spec:
  encryptedData:
    .dockerconfigjson: AgCyeqoeommM3jTXSh0ixWNBXUtqpw53I5HFQQrrSkb1A0YTx6LVtoQVPzcBGO//pjuIBYd6N13svxby5RsRZ19RNGR3e4T9AdL/ta+d4HtPScMp0Oj/JkcjH3kSuE1/6H/XiXrsv0j7cR7GhNBg1+jTT8th2VskrsV+nYIFMcrgFunrxGaMWKtOg8QpGzrTgp1GtZ4gY7RaNarYtCzNSfN+t/SL4iARW3j8tugfqu7Ex7Lp90ZA7jI8MN8mhXKDDS8Fd+4VtIJSQr4bXUM5TWc0jF36gYux5a3IeQaZ3GD4Ucd/Krl4kPQWp/n9OG9XXOl2wAFZ+dRJ3Q07YRXOpoWQqXZymjX7ywL/ZFgvlA93M8uCa6SXX3SHq92pquoBTQi59QvIg0ioJwC5an2CbGei03wtXUsjZ1o+xGOv6CjX0094/RiTU47sUYVU/uIdLGTcL4gph03gQF1cKktjtzDoQt4XDOkR5y6R3INd43CDC/DF/8NRnEnsjpVw0sD2fY0/20bU8p1hD9f+0iupQ2FOHI/cXnuzZ/PWRQYJzHdMbRR5iAz2qOgJu1xM+cA5txvCW8cG71S9I/Bs2lotIPs7+0t/qqiDPoTO1Tl+KE3CED0+fAONpbhPoZLIIwOFcntaK5CklJc1AFQCiUsVSBcr6/Y738Y5R3uOE9BBKowJ3uhQrwrqKUVg/NbXvz6HuZ6U6psVwP2Kkx3EmkGHEnRuCEwlbQADTD/yxxkbX/W5FUzfHOrj4nYlCHjXQqUY2PID/LAuqtO0LsXh/UR9ErPgj1J7AbTups65ZaW7HsWrRBLhBzxYiIRP/kU/b9pf1X1+lCmLUoqLAp/F2vMAvb7svCvNzc6177288oHFNjYCGOHe6l3tRVw8WquQnJbnTp4lKPSz9S0u3DvhysRVt4jjy4C4vuA5Z9k/LdjZa13G6EUePdkmwY5woW7EqRQyMiN8lJ8acBP/0u2dCK7z9w65aw6iYCg1kyl+
  template:
    metadata:
      creationTimestamp: null
      name: github
      namespace: findingway
    type: kubernetes.io/dockerconfigjson
