---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: env
  namespace: findingway
spec:
  encryptedData:
    DISCORD_TOKEN: AgCpZVprWb6dHUYR8k/wVgfBuXS1g8zjaf4B4hGRvikozOJK/1hewgUS5y2emcN4vK7M5jjekn5vlVh9g7CZ6/V27g6I8i0JU5/UQd31uu/GthBjelYX92SBxCyng+1yTRb99UiK1StMC9EWUbiT+DTdUJJVEhgm6zoNpf16MpNdqJaAf3+y6EtHlorgE+iPIgd26b+LYz6krXnKZjnI6LAKRB3zCCmhczGgx76L7LXIHNXAfGabmhXHtmfT8nhUZaQJs0EF4MXoVP1MKS0HhprW1JlNM2oY5hNjWPa3GPXYDbErdBLY4K7l/JoXRROYDjys/1bc+UuaC0kBqHwezozIZL8TXDC8E198Xg5bb3QgsfCtysYFU66LW+IIkjMPLlMGG640gDbralR/wDmVdZ+VA5HgiWTbFWvsUXN/2gfeO9SV7GWdAKaEpXMbgmrJ30YGrAfimCD0lOipntyB18NaG26WzXuoYu7rPt7cuDm3MG0Bx0zP3zOtEA+2LS3IVaCxYGcvRsfUEn9CasP7RB+H5vYARnS7xMGJpHM8cLJ5284dIMVWzqIcrAq1VG1en6/prw4gaYlhnDMTyH4FsWZIwvynrbG5bAnBXKYgauKT0XxP+g4wEa58TD0npuFbfVXrevphzqjJicmnUpvr4Ro2LzL62Y9uqE8VehQPAxr+gKv9eokNFSPFMi6DMg1BvOT2IV3L+g/VWWIBfa2QnBN025af+O+6kc7fnWw45PtqVJ9rGH/VNjVEPMIMdZmRdQQrISlL+1fwUWe6doonjXWK6FjmG2Q+cQ==
  template:
    metadata:
      creationTimestamp: null
      name: env
      namespace: findingway
