---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: env
  namespace: findingway
spec:
  encryptedData:
    FINDINGWAY_DISCORD_TOKEN: AgB3FVypTTOBMYpPvAJOy2dWwggs7LfSxOiXAzD+ewW8iFOAvI4tCIp/AYIE7/IMRa19IU+/zw+gtAp1dwIiGrtrCCA1CkJG8yCy5reg7FjUef4fMNMQ8YUPTDEmpv6G9GevXLLs9CCLu6K0MUCOTxpxGs2EeIgQYcg3/xGs40SO+XUZmYjaQv29rjgP1/1ROoYnMUnWbFS8WpVz5J3VMpQeDS789l2fWDuR/wecbA1Ja3lrG6Gl/MgV1wk0js3N1t434N3mVIKTrC2sJFWC9lE1B3pdXG/kIf/bOqymM9nyZ5ofi0ZibhPHU3tQcI0e4B0+HZqIaXkqhwSNH3XeKVPKEnJHErwqaKSW9DWhaZgs0LZuN9+95Wo5XFbvHh6QLWKW+cJUXkmXVUXeFgnx+d/Nqj+yfn/qg85sEHreY2fE6NSEzaeyjspRinZK1IGGZCxPcG8SM4ghPXZk+bDuXrMOXZ+kJM1DTq8VWo4zMgxIVbtmfdnSHOQ+DrXbqvzlu58d71HTW5AIp1GCGxCvAnb9usHpG6TGBaEdHamGFhbDiFhe5gxjaM5QzlyvsirbdT34soRUpKhfyzD7YKMj64FciFPbVA54VLdpr9yXCTmNj+zyLeDnQBwg7KX+ga6E6kG2q+qN9DKr0jwhx1Y75PJ98UIjkn4TTIIAyFkj2b6RSJRHH3FpO8F1gWlodCDe3EtN8JiDlCvF09yESya4FBClOiW361h6+q3BkR8F4cABUFe6oOIHnErvFv8j7lulAm794gQ45Ur+nZDtV54Zzqc+6K6vUSxAtdo=
    FINDINGWAY_POSTGRES_URL: AgDbHZ3TgmrkUBaTjaKXQ6UMCIj7l2igYZohk1FpFA5Bbpml2YZLBTXWMBN91cOtugMFYnWCxvznl8Zv5cowPBaN3hxmKJ+2bejQhN1XxgBq4FvIzTkW8AIg5NbIwxYOQX/7FNgk2aYn1vIywfl/fUjjRn+hT+QpVAiPwDrV8nTHJivZMdE4Y+MtG9roG/XQGcnQjuzxxJ6IsAZgiTRFRazLuYM67F6P/Ex2z5AL3XM3wzOeb1lEWz1zpnGl1eE6EjNSxaAfNu5riTtkUnzwwpLRvxC5DkpLRIvuy1Odbb2qxBLV1kunVofidUuT2rblMI9TRSh7cq5UXTvYppY3e7smdEJgl353rkw4/gUKz9iNRT+xIaq0LwqFVM3hS+Jk8zHqUavQA4aFwGAxUGsED8j9tCL8WelJPjg5rBju6DY4BxjA2DJLzfz3TrieV2QShMngcgoT0/3IgB+yhxenmYwWVhNQJgcoqEJMc2z9PHIzdro3O9iw2wSSWHLrFrEq2vbtGyDjRe8g8B2JiE31QjyDtu95+NRGKCMkjKTSdJ1HMHNOSH5Pu2MYfxLBVjpjhOBJdHIc135euzBaGUmig4XNc/z16zltlkJdatBwzIldkh1tWnmOoywVFJ0b/c0L4yhrRulOTcZTQwsiCNbO5oAMZg3Ts2lhi/N0Ik/qsYQWJxmx7ntojNLM+s13NphiHgzBr3UyqXF9Xaqec9NCkNCh4Y5Ayr29UQLec4Tt0rWEr16Kfq+qGb54+L9TYNQcIun9Or5tYCHTL4VI8LnNv2mT8UJr/a+FHdWsh9PjKRn2qKmqiFJ37sY93vJsoqywYaZtsearlIhSjR3KbLPj3nL4XHAze4IzXCzP8c1CzCmGo3486C4T
  template:
    metadata:
      creationTimestamp: null
      name: env
      namespace: findingway
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github
  namespace: findingway
spec:
  encryptedData:
    .dockerconfigjson: AgDUm96aSsfYFLVs7IqSLMYelzRVEES40J0zHyF1MG3R9Le4dqeaEhhxuYj+GmLKKf/iBlEQA3UCOlNKyu5U1IxUXkxRwiUOOJXg+O+/2J79yxCXeJTbW3XJIykaq84a/BtsYdiKdDYKCmm600PRyvEdQ0YzJ24nEwbJj24NawBJsnLXe5JiuZlSeqHFZbPO5BsfC96PR4ik2iahTNTVr9buxrSQlNBGp5AfCT7eOeLeYed5JdWi8+CagxKfsUPcvRXTSHZPtxI0C87GyLhxL3fXsCqxhd2tUIElDhKnqDVg8ZnipuuA8hHJq0VibDJubc1pMNPN1KR8TMKFunL/qAlfubn+TpHQYlas9wzpaCv354uT59pnDS3JKSE6Gds1yDNbJLS3x0YmCNBKtOtFe6cnT6f9SLfi7LJDd/J5SZpwPIYUU5hnBDBPt8hQqAourRWCsMxdvtitHQawzTLVcU6U/v2HVPNHJAwQx4rOf4dp7ZuWaH7bC05X9/C+Codc7GXttlOVOD+cXq0ZuyqgMy5Ho0ADV3qGB1gD+0PZ6a1a2Np7RiUbO1scHMMdILYEuyOrCUJnRkOkwYYh4wGpLy5YVfxfI8JKrziUI/0SI3L+as4oD0wt6+eStzJRKJkLwKOHYFKwl0C4vAqOqMutqDS5hOZwbLQJXlKprNZuFt1QtkvHfBYDc44HsMnXPdb+a5xHoejkeSrm3B44n7IaTBPqi3xSFdh4wn24Qn8KnQSRfRodhhf1yNHcLc/sMZbST6xiZaCMnoyhY+cRxKM6y+EEeVvnFeSJfIblrtKdBxTdO1GefXuJrkSuKvXF5CA0UPn3KorugauJyWthOW8JljH3Bje1DA+g1BJe9v+ZEYXlHFuLf2A2uQH6+CpyQTAN5gv1dIHEf2I5TknjQlOKOUNDutawgXVx0Zmm+Ne7U4QJ7UzN1MiQlx1O7AL38fk5Kbp7hkI595GkZa4MMiwqouu4XTo/uMrBPZvT
  template:
    metadata:
      creationTimestamp: null
      name: github
      namespace: findingway
    type: kubernetes.io/dockerconfigjson
